spring.application.name=cafecito

# URL de conexión
spring.datasource.url=jdbc:postgresql://ep-dry-rain-aivo4o6y-pooler.c-4.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_fQx78mdEKJIT&sslmode=require&channelBinding=require

# PostgreSQL - Credenciales
spring.datasource.username=neondb_owner
spring.datasource.password=npg_fQx78mdEKJIT

# PostgreSql driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Zona horaria y dialecto
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

api.security.token.secret=${JWT_SECRET:fx5buBA34utyk29LFsknk79qSrvk2TLs7R+LO2qhtFo=}
